---
- name: To install nginx and start the service
  become: true
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: latest
      notify: Start nginx
    - name: Create index.html
      ansible.builtin.copy:
        content: 'Welcome to Ansible Nginx!'
        dest: /var/www/html/index.html
        mode: '0644'
        owner: root
        group: root
      notify: Start nginx
  handlers:
    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes


